import os

__all__ = [
    "RUNTIME_PATH",
    "FLET_APP_STORAGE_TEMP",
    "FLET_APP_STORAGE_DATA",
    "APP_VERSION",
    "BUILD_VERSION",
    "PROTOCOL_VERSION",
]

RUNTIME_PATH = os.environ.get("PYTHONHOME", "")
FLET_APP_STORAGE_TEMP = os.environ.get("FLET_APP_STORAGE_TEMP", ".")
FLET_APP_STORAGE_DATA = os.environ.get("FLET_APP_STORAGE_DATA", ".")

DEFAULT_WINDOW_TITLE = "CFMS Client"

BUILD_VERSION = "v0.2.15"
APP_VERSION = f"{BUILD_VERSION[1:]}.20251011_alpha NEXT"
PROTOCOL_VERSION = 3
GITHUB_REPO = "Creeper19472/cfms_client_next"

INTEGRATED_CA_CERT = """
-----BEGIN CERTIFICATE-----
MIICazCCAhCgAwIBAgIUMOJM76aCZ/5MXqL3fxaQbPvYJoMwCgYIKoZIzj0EAwIw
ejELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWpp
bmcxJTAjBgNVBAoMHENGTVMgTWFuYWdlbWVudCBPcmdhbml6YXRpb24xIDAeBgNV
BAMMF0NGTVMgVmFsaWRhdGlvbiBSb290IENBMB4XDTI1MDkxOTA0MzQyMFoXDTI4
MDkxODA0MzQyMFowgYcxCzAJBgNVBAYTAkNOMRAwDgYDVQQIDAdCZWlqaW5nMRAw
DgYDVQQHDAdCZWlqaW5nMTUwMwYDVQQKDCxDRk1TIEludGVybWVkaWF0ZSBDQSBN
YW5hZ2VtZW50IE9yZ2FuaXphdGlvbjEdMBsGA1UEAwwUQ0ZNUyBJbnRlcm1lZGlh
dGUgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARUHTvzub/uwfCcFHZdnliF
IGghm1ZNxdKjYjeYMZs87uu8AjJVtG9MBV0+bnj9uzzYDoQ2+5u2gccB4ETiT6mB
o2YwZDASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4E
FgQU5YWPQ5jiWFP+M3bAJrk/iGzigeMwHwYDVR0jBBgwFoAUYgHVcHEiM4gP4gSA
oIMUKCQGBv4wCgYIKoZIzj0EAwIDSQAwRgIhALrCHuX8oDwF5GJyekkH3DNdAmVq
d2diSMQPL3P1eKxNAiEA9hIiXGee0/VWU6rchoDpu2Zgfm+O9Qea9w24byIHk4A=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIICNzCCAd6gAwIBAgIUQuVdzgZ7uk+3zgD0PMAW19qvVFMwCgYIKoZIzj0EAwIw
ejELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWpp
bmcxJTAjBgNVBAoMHENGTVMgTWFuYWdlbWVudCBPcmdhbml6YXRpb24xIDAeBgNV
BAMMF0NGTVMgVmFsaWRhdGlvbiBSb290IENBMB4XDTI1MDkxOTAxNTQxNloXDTM1
MDkxNzAxNTQxNlowejELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAO
BgNVBAcMB0JlaWppbmcxJTAjBgNVBAoMHENGTVMgTWFuYWdlbWVudCBPcmdhbml6
YXRpb24xIDAeBgNVBAMMF0NGTVMgVmFsaWRhdGlvbiBSb290IENBMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEInAqo8eO4cRgC4qIb1kiHNt6f7D4m6WssYXkgpJ5
juoftDfX5pyiwsk8jwSdFqiheZDa7s2R5RyyA9kmS6IJ36NCMEAwDwYDVR0TAQH/
BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0OBBYEFGIB1XBxIjOID+IEgKCD
FCgkBgb+MAoGCCqGSM49BAMCA0cAMEQCIGqVCctVrbOpZlUZ/7B7b+rgdHVgaBqZ
wVDBU9HfMfz7AiB0mZmZpt9e4GpvLuK8uFuyGLDxYzMrbRuqByRWG1q8Xg==
-----END CERTIFICATE-----
"""
