"""Application-wide constants and configuration values."""

import os
from pathlib import Path
from .classes.version import ChannelType


__all__ = [
    "RUNTIME_PATH",
    "FLET_APP_STORAGE_TEMP",
    "FLET_APP_STORAGE_DATA",
    "APP_VERSION",
    "BUILD_VERSION",
    "PROTOCOL_VERSION",
    "DEFAULT_WINDOW_TITLE",
    "GITHUB_REPO",
    "INTEGRATED_CA_CERT",
    "DEFAULT_UPDATE_CHANNEL",
]

# Path Configuration
CONSTANT_FILE_ABSPATH = os.path.abspath(__file__)
ROOT_PATH = Path(CONSTANT_FILE_ABSPATH).resolve().parent.parent
LOCALE_PATH = f"{ROOT_PATH}/include/ui/locale"
RUNTIME_PATH = os.environ.get("PYTHONHOME", "")
FLET_APP_STORAGE_TEMP = os.environ.get("FLET_APP_STORAGE_TEMP", ".")
FLET_APP_STORAGE_DATA = os.environ.get("FLET_APP_STORAGE_DATA", ".")
USER_PREFERENCES_PATH = f"{FLET_APP_STORAGE_DATA}/user_preferences"

# Application Info
DEFAULT_WINDOW_TITLE = "CFMS Client"
GITHUB_REPO = "Creeper19472/cfms_client_next"

# Version Information
CHANNEL = ChannelType.STABLE
BUILD_VERSION = "v0.6.0"
MODIFIED = "20260220"

# Default update channel for user preferences
DEFAULT_UPDATE_CHANNEL = ChannelType.STABLE

if CHANNEL == ChannelType.STABLE:
    APP_VERSION = f"{BUILD_VERSION[1:]}.{MODIFIED} NEXT"
else:
    APP_VERSION = f"{BUILD_VERSION[1:]}.{MODIFIED}_{CHANNEL.value} NEXT"

# Protocol
PROTOCOL_VERSION = 9

# Integrated CA Certificate for SSL
INTEGRATED_CA_CERT = """
-----BEGIN CERTIFICATE-----
MIICazCCAhCgAwIBAgIUMOJM76aCZ/5MXqL3fxaQbPvYJoMwCgYIKoZIzj0EAwIw
ejELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWpp
bmcxJTAjBgNVBAoMHENGTVMgTWFuYWdlbWVudCBPcmdhbml6YXRpb24xIDAeBgNV
BAMMF0NGTVMgVmFsaWRhdGlvbiBSb290IENBMB4XDTI1MDkxOTA0MzQyMFoXDTI4
MDkxODA0MzQyMFowgYcxCzAJBgNVBAYTAkNOMRAwDgYDVQQIDAdCZWlqaW5nMRAw
DgYDVQQHDAdCZWlqaW5nMTUwMwYDVQQKDCxDRk1TIEludGVybWVkaWF0ZSBDQSBN
YW5hZ2VtZW50IE9yZ2FuaXphdGlvbjEdMBsGA1UEAwwUQ0ZNUyBJbnRlcm1lZGlh
dGUgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARUHTvzub/uwfCcFHZdnliF
IGghm1ZNxdKjYjeYMZs87uu8AjJVtG9MBV0+bnj9uzzYDoQ2+5u2gccB4ETiT6mB
o2YwZDASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4E
FgQU5YWPQ5jiWFP+M3bAJrk/iGzigeMwHwYDVR0jBBgwFoAUYgHVcHEiM4gP4gSA
oIMUKCQGBv4wCgYIKoZIzj0EAwIDSQAwRgIhALrCHuX8oDwF5GJyekkH3DNdAmVq
d2diSMQPL3P1eKxNAiEA9hIiXGee0/VWU6rchoDpu2Zgfm+O9Qea9w24byIHk4A=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIICNzCCAd6gAwIBAgIUQuVdzgZ7uk+3zgD0PMAW19qvVFMwCgYIKoZIzj0EAwIw
ejELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWpp
bmcxJTAjBgNVBAoMHENGTVMgTWFuYWdlbWVudCBPcmdhbml6YXRpb24xIDAeBgNV
BAMMF0NGTVMgVmFsaWRhdGlvbiBSb290IENBMB4XDTI1MDkxOTAxNTQxNloXDTM1
MDkxNzAxNTQxNlowejELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAO
BgNVBAcMB0JlaWppbmcxJTAjBgNVBAoMHENGTVMgTWFuYWdlbWVudCBPcmdhbml6
YXRpb24xIDAeBgNVBAMMF0NGTVMgVmFsaWRhdGlvbiBSb290IENBMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEInAqo8eO4cRgC4qIb1kiHNt6f7D4m6WssYXkgpJ5
juoftDfX5pyiwsk8jwSdFqiheZDa7s2R5RyyA9kmS6IJ36NCMEAwDwYDVR0TAQH/
BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0OBBYEFGIB1XBxIjOID+IEgKCD
FCgkBgb+MAoGCCqGSM49BAMCA0cAMEQCIGqVCctVrbOpZlUZ/7B7b+rgdHVgaBqZ
wVDBU9HfMfz7AiB0mZmZpt9e4GpvLuK8uFuyGLDxYzMrbRuqByRWG1q8Xg==
-----END CERTIFICATE-----
"""
